var acer = [{
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}
];
var asus = [{
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}];
var dell = [
    {
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }
]
var hp =[
    {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },
];
var lenovo = [
    {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },
]
var nav = document.querySelector("#nav-tabContent");
for(var i = 0;i<acer.length;i++){
// var div = document.createElement("div");
// div.classList.add("tab-pane fade show active");
var img = document.createElement("img");
img.setAttribute("src","images/Acer.jpg");
nav.appendChild(img)
// div.appendChild(img);

}