var acer = [{
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "acer",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}
];
var asus = [{
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}, {
    ad: "Asus",
    tesvir: "tesvir",
    qiymet: "2780 AZN",
    telefon: "055-867-3567",
    yeni: "bəli",
    əməliyaddaş: "16GB",
    CPU: "Core i9",
    daimiyaddaş: "500GB",
    daimitipi: "SSD",
    emeliyyat: "win 10",
    GPU: "Intel Iris Xe Graphics"
}];
var dell = [
    {
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },{
        ad: "dell",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }
]
var hp =[
    {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },  {
        ad: "hp",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },
];
var lenovo = [
    {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    }, {
        ad: "lenovo",
        tesvir: "tesvir",
        qiymet: "2780 AZN",
        telefon: "055-867-3567",
        yeni: "bəli",
        əməliyaddaş: "16GB",
        CPU: "Core i9",
        daimiyaddaş: "500GB",
        daimitipi: "SSD",
        emeliyyat: "win 10",
        GPU: "Intel Iris Xe Graphics"
    },
]
var nav = document.querySelector("#nav-tabContent");
for(var i = 0;i<acer.length;i++){
var div = document.createElement("div");
div.classList.add("width-20");
div.classList.add("p-3");
var box = document.createElement("div");
box.classList.add("box");
var ad = document.createElement("p");
ad.innerHTML = `<p><span class = "badge rounded-pill bg-primary" >Ad</span>:${acer[i].ad}</p>`;
var yeni = document.createElement("p");
yeni.innerHTML = `<p><span class = "badge rounded-pill bg-primary" >Yenidir</span>:${acer[i].yeni}</p>`;
var telefon = document.createElement("p");
telefon.innerHTML = `<p><span class = "badge rounded-pill bg-primary" >Telefon</span><span id="small">:${acer[i].telefon}</span></p>`;
var qiymet = document.createElement("p");
qiymet.innerHTML = `<p><span class = "badge rounded-pill bg-primary" >Qiymet</span>:${acer[i].qiymet}</p>`
var buton = document.createElement("button");
buton.classList.add("btn");
buton.classList.add("btn-primary");
buton.classList.add("ms-4");
buton.innerText = "Ətraflı";
var img = document.createElement("img");
img.setAttribute("src","images/Acer.jpg");
box.appendChild(img);
box.appendChild(ad);
box.appendChild(telefon);
box.appendChild(yeni);
box.appendChild(qiymet);
box.appendChild(buton);
div.appendChild(box);
nav.appendChild(div)
}